### ISSUE TITLE
Mostrar media de minutos de llamadas salientes

### ISSUE THREAD

**Issue by aalmenar** [jmsanzg/myPlan#104]
Ahora en la sección de estadísticas se muestra la media de tiempo de llamadas entrantes y salientes.

Veo que hay espacio y me parecería razonable tener una media de llamadas salientes ya que estas son las que tienen coste (Al menos en España y la gran mayoría del mundo).

**Comment by aalmenar** [comment]
Si estas de acuerdo con este cambio indicamelo asi hago commit y un pull request para añadirlo al código base.

**Comment by jmsanzg** [comment]
Me parece perfecto, pero ya que estás, mejor tener ambas, media de llamadas entrantes y media de llamadas salientes ¿qué te parece?

**Comment by aalmenar** [comment]
Solucionado en el pull request #108

**Comment by aalmenar** [comment]
Cerrando esta.
