### ISSUE TITLE
Movistar Contrato Tiempo Libre

### ISSUE THREAD

**Issue by jmsanzg** [jmsanzg/myPlan#31]
(Reportado por Ángel Plaza)

Durante el fin de semana el precio por minuto es a 8cent y no 30cent.

http://www.tarifas.movistar.es/particulares/voz/contratotiempolibre

https://github.com/jmsanzg/myPlan/blob/master/src/com/conzebit/myplan/ext/es/movistar/particulares/ESMovistarContratoTiempoLibre.java

**Comment by DarkEagle82** [comment]
Este issue se podria cerrar no ?

**Comment by jmsanzg** [comment]
Correcto. Solucionado por Angel Plaza en el commit edce12335d6b6bd319f5c5b029b55260029cbf0a

Por cierto, se me olvidó meterle en los agradecimientos...ahora mismo actualizo los datos de la versión en el Market!!
