### ISSUE TITLE
Actualizada Tarifa Delfin 20 Orange

### ISSUE THREAD

**Issue by charlystrength** [jmsanzg/myPlan#39]
La tarifa Delfín 20 ha sido actualizada hace unos pocos días, incluyendo llamadas gratuitas 24 horas los fines de semana y festivos (antes, TODOS los días eran gratis de 18h a 8h), y ahora incluye 200 MB, en lugar de 100.

**Comment by jmsanzg** [comment]
el usuario @DarkEagle82 (Sergi) ha actualizado ya dicha tarifa. La siguiente
anmate t mismo!! :-)

No tardar mucho en crear una nueva versin y subirla al Market

un saludo

Josmi

2011/9/10 charlystrength <
reply@reply.github.com>

> La tarifa Delfn 20 ha sido actualizada hace unos pocos das, incluyendo
> llamadas gratuitas 24 horas los fines de semana y festivos (antes, TODOS los
> das eran gratis de 18h a 8h), y ahora incluye 200 MB, en lugar de 100.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jmsanzg/myPlan/issues/39

## 

Jos Miguel Sanz
www.conzebit.com
http://github.com/jmsanzg
https://plus.google.com/109926625077500376549
