### ISSUE TITLE
Tarifas Eroskimovil

### ISSUE THREAD

**Issue by Pinazinho** [jmsanzg/myPlan#45]
Hola, como puedo añadir las tarifas de Eroski movil?
Por ejemplo:

Tarifa contigo
Establecimiento 0 €
Consumo mínimo 0 €
0,10 €/minuto
0,10 € SMS

**Comment by jmsanzg** [comment]
Haz un fork de myPlan, programas la tarifa correspondiente y luego pides un "pull request".

Toda la info aquí: http://help.github.com/fork-a-repo/

**Comment by Pinazinho** [comment]
Ya me he bajado el codigo fuente original y he programado las tarifas correspondientes, pero al intentar hacer el "pull request" me dice "Oops! The jmsanzg:master branch is already up-to-date with Pinazinho:master — maybe you want to try something else?"
Puedes echarme una mano para subir los cambios?

**Comment by jmsanzg** [comment]
hiciste commit en local entiendo, luego hiciste push de esos cambios a
github?

ten en cuenta que git no es como cvs/svn, cuando haces commit lo haces sobre
un repositorio en tu pc y slo se sube a github cuando llamas a push. El
comando debera ser algo como:

$git push git@github.com:pinazinho/myPlan

Un saludo

JosMi

2011/10/18 Pinazinho <
reply@reply.github.com>

> Ya me he bajado el codigo fuente original y he programado las tarifas
> correspondientes, pero al intentar hacer el "pull request" me dice "Oops!
> The jmsanzg:master branch is already up-to-date with Pinazinho:master 
> maybe you want to try something else?"
> Puedes echarme una mano para subir los cambios?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jmsanzg/myPlan/issues/45#issuecomment-2441044

## 

Jos Miguel Sanz
www.conzebit.com
http://github.com/jmsanzg
https://plus.google.com/109926625077500376549

**Comment by Pinazinho** [comment]
Exacto, ese era el problema.
Ya he podido hacer push y te he solicitado el pull request.

Una pregunta: las actualizaciones del código fuente que hagamos aquí las mandas directamente al Android Market para que la gente se actualice el myPlan o te esperas a que hayan varios cambios y sacar una versión nueva?

Un saludo!

**Comment by jmsanzg** [comment]
Hola, ahora har el code review.

Respecto a la pregunta, habitualmente espero a que haya varias
actualizaciones antes de generar un apk para mandarlo al Market pero ahora
mismo tengo ya varios issues cerrados y, si veo lo tuyo correcto, har
versin inmediatamente.

Por cierto, si quieres decirme tu nombre para que aparezca en los
agradecimientos o en caso contrario indicar tu alias de github "Pinazinho".

Por otro lado, no he mirado todava el cdigo, espero que te hayas puesto
como @author de los planes y de los cambios :)

un saludo

JosMi

2011/10/18 Pinazinho <
reply@reply.github.com>

> Exacto, ese era el problema.
> Ya he podido hacer push y te he solicitado el pull request.
> 
> Una pregunta: las actualizaciones del cdigo fuente que hagamos aqu las
> mandas directamente al Android Market para que la gente se actualice el
> myPlan o te esperas a que hayan varios cambios y sacar una versin nueva?
> 
> Un saludo!
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jmsanzg/myPlan/issues/45#issuecomment-2441389

## 

Jos Miguel Sanz
www.conzebit.com
http://github.com/jmsanzg
https://plus.google.com/109926625077500376549

**Comment by jmsanzg** [comment]
Podemos dar este issue por cerrado :)
