### ISSUE TITLE
Solucionar problema con Ardilla 15 Orange

### ISSUE THREAD

**Issue by charlystrength** [jmsanzg/myPlan#46]
Buenos días, la reciente tarifa Ardilla 15 de Orange necesita ser corregida, en mi terminal me contabiliza un total de 340€ gastados, cuando llevo menos de 30€.

Recuerdo que la Ardilla 15 tiene 8 cents/min a cualquiera las 24 h todos los días, 150sms gratis y 150mb de internet a máxima velocidad, así como un establecimiento de llamada de 15 cent (precios sin iva).

Muchas gracias.

**Comment by jmsanzg** [comment]
Problema corregido, ¡¡gracias por informar!!

**Comment by charlystrength** [comment]
Mil gracias!!!
