### ISSUE TITLE
Descontar cuota mensual Ardilla 15 Orange

### ISSUE THREAD

**Issue by charlystrength** [jmsanzg/myPlan#49]
Buenos días, hay un problema con la contabilización de la tarifa Ardilla 15 de Orange. La cuota mensual de 11,80 se computa en un consumo mínimo de 17,70€, por lo que no debería sumarse al importe de las llamadas.

Actualmente, se suma el importe de las llamadas más 11.80, cuando esos 11.80 se van "rellenando" con el importe de las llamadas. Es decir, en la tarifa Ardilla 15 se contabiliza el importe de las llamadas más el establecimiento, y el resultado final es lo que pagas, a no ser que gastes menos que el consumo mínimo, en cuyo caso se pagaría 17.70 de todos modos.

No sé si me he explicado, es algo lioso. La solución sería no sumar esos 11.8 mensuales y simplemente contabilizar las llamadas, los establecimientos y los sms fuera de los 150 gratis. Si el total es menos de 17.70 (consumo mínimo), se paga 17.70 de todas formas.

Si supiese manejar código lo haría yo mismo encantado...mil gracias!!

Por cierto, hay forma de incluir números VIP??

**Comment by jmsanzg** [comment]
Hola,

hasta donde entiendo la aplicacin ahora mismo saca un listado como el
siguiente (acabo de comprobarlo):
- Consumo mnimo: 15
- ... (todas las llamadas hechas)
- Diferencia consumo mnimo: 2,55 (en mi caso de prueba ya que el consumo
  mnimo < 15)

de este modo me indica que el total que tendra que pagar es 15 (+IVA).

Mirando la tarifa veo que eso es exctamente lo que tiene que hacer el plan
a no ser que no me haya enterado de la explicacin ;)

Respecto a la pregunta, no, ahora mismo no hay posibilidad de incluir
nmeros VIP a no ser que el coste de esos vip sea 0 en cuyo caso basta con
pulsar sobre ellos y seleccionar "Coste 0".

Un saludo

2011/10/19 charlystrength <
reply@reply.github.com>

> Buenos das, hay un problema con la contabilizacin de la tarifa Ardilla 15
> de Orange. La cuota mensual de 11,80 se computa en un consumo mnimo de
> 17,70, por lo que no debera sumarse al importe de las llamadas.
> 
> Actualmente, se suma el importe de las llamadas ms 11.80, cuando esos
> 11.80 se van "rellenando" con el importe de las llamadas. Es decir, en la
> tarifa Ardilla 15 se contabiliza el importe de las llamadas ms el
> establecimiento, y el resultado final es lo que pagas, a no ser que gastes
> menos que el consumo mnimo, en cuyo caso se pagara 17.70 de todos modos.
> 
> No s si me he explicado, es algo lioso. La solucin sera no sumar esos
> 11.8 mensuales y simplemente contabilizar las llamadas, los establecimientos
> y los sms fuera de los 150 gratis. Si el total es menos de 17.70 (consumo
> mnimo), se paga 17.70 de todas formas.
> 
> Si supiese manejar cdigo lo hara yo mismo encantado...mil gracias!!
> 
> Por cierto, hay forma de incluir nmeros VIP??
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jmsanzg/myPlan/issues/49

## 

Jos Miguel Sanz
www.conzebit.com
http://github.com/jmsanzg
https://plus.google.com/109926625077500376549

**Comment by charlystrength** [comment]
A lo que me refiero es que ahora mismo pincho en el desglose de la Ardilla 15, y primero me aparece cuota mensual 11.8 y luego el listado de cada llamada con su precio. Así, la aplicación suma 11.8 más el importe de cada llamada. Sin embargo, esos 11.8 no se pagan a parte de lo que se va consumiendo, sino que  lo que se va consumiento computa en esos 11.8 y los 17.7 de mínimo mensual (lo que no entiendo muy bien de la tarifa es por qué han puesto tarifa mensual y luego consumo mínimo...). Por ejemplo, ahora mismo me pone que llevo 39.84€, cuando en realidad llevo 28.04.

Espero haberme explicado mejor! Mira la web de la tarifa por si tienes alguna duda o lo he interpretado mal, pero el operador de Orange me lo explicó justo así cuando llamé para cambiarme.

Mil gracias de nuevo!

**Comment by charlystrength** [comment]
Por ejemplo, hoy es mi primer día de tarifa, y antes de realizar la primera llamada, myPlan dice que llevo gastado 17.70 (el consumo mínimo). Después de realizar una llamada, me pone que llevo gastado 18.30, cuando no es cierto, llevo gastado 60 cent. Las llamadas deberían acumularse o "rellenar" esos 17.70, y cuando ya se hayan superado, entonces se comienza a sumar.

Espero haberme hecho entender, ya me contarás!!

**Comment by charlystrength** [comment]
Ok, tuve un problema en la instalación o algo, he desinstalado y vuelto a instalar y funciona ok. Cierro el tema si te parece bien, y si al final de mi mes de facturación hay algún fallo ya lo comentaré. Muchas gracias!!

**Comment by jmsanzg** [comment]
ok, lo hacemos as. En cualquier caso revisar el cdigo de nuevo.

gracias por informar de los errores!

josmi

2011/10/23 charlystrength <
reply@reply.github.com>

> Ok, tuve un problema en la instalacin o algo, he desinstalado y vuelto a
> instalar y funciona ok. Cierro el tema si te parece bien, y si al final de
> mi mes de facturacin hay algn fallo ya lo comentar. Muchas gracias!!
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jmsanzg/myPlan/issues/49#issuecomment-2494402

## 

Jos Miguel Sanz
www.conzebit.com
http://github.com/jmsanzg
https://plus.google.com/109926625077500376549
